# Cloudflare Pages 部署配置

build:
  command: cd frontend && npm install && npm run build
  publish: frontend/out
  
environment:
  NODE_VERSION: "18"
  NPM_VERSION: "9"
  
build_settings:
  root_dir: "/"
  build_command: cd frontend && npm install && npm run build
  publish_directory: frontend/out
  
functions:
  node_compat: true
  
# 环境变量 (需要在 Cloudflare Pages 控制台中设置)
environment_variables:
  - RUNPOD_API_KEY
  - RUNPOD_ENDPOINT_ID
  - NEXT_PUBLIC_API_URL 